config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
    
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

posts/urls.py
from django.urls import path

from posts.views import *
# (*
#     feeds,
#     comment_add,
#     comment_delete,
#     post_add,
#     tags,
#     post_detail,
#     post_like,
#     post_delete,
# )

app_name = "posts"
urlpatterns = [

    # path("comments/<int:comment_id>/delete/", comment_delete, name="comment_delete"),
    # path("post_add/", post_add, name="post_add"),
    # path("<int:post_id>/", post_detail, name="post_detail"),
    # path("post/<int:post_id>/delete/", post_delete, name="post_delete"),    
    # path("comment_add/", comment_add2, name="comment_add2"),


    path("feeds/", feeds2, name="feeds"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("tags/<str:tag_name>/", tags2, name="tags2"),
    path("<int:post2_id>/", post_detail2, name="post_detail2"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_addtag/", comment_addtag, name="comment_addtag"),

    path("<int:post2_id>/like/", post_like2, name="post_like2"),
    path("post_add/", post_add, name="post_add"),
    
    path("post_add2/", post_add2, name="post_add2"),
    path("comments/<int:comment_id>/delete/", comment_delete2, name="comment_delete2"),

    path('text_entry_list/', text_entry_list, name='text_entry_list'),
    path("admin1/aa/", admin1, name="admin1"),
    path("date_range_view/delete_row/<int:row_id>", delete_row, name="delete_row"),
    path("admin1/aa/delete_row/<int:row_id>", delete_row, name="delete_row"),

    path("admin2/delete_row2/<int:row_id>", delete_row2, name="delete_row2"),
    path("admin2/", admin2, name="admin2"),
    path('create/', create_text_entry, name='create_text_entry'),
    
    path('admin1/aa/', date_range_view, name='date_range_view'),
    path('download_csv/', download_csv, name='download_csv'), #### 추가한다. 

    path('../../admin/', to_admin, name='to_admin'), #### 추가한다. 
    path("admin3/", admin3, name="admin3"),
    path('create_note/', create_text_entry_note, name='create_text_entry_note'),#### 여기는 공지사항
    path("admin3/delete_row3/<int:row_id>", delete_row3, name="delete_row3"),
]

users/urls.py
from django.urls import path

from users.views import *
# (
#     login_view,
#     logout_view,
#     signup,
#     profile,
#     followers,
#     following,
#     follow,
# )

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
 
 
    path("<int:user_id>/profile/", profile2, name="profile2"),
    path("my_update/", my_update, name="my_update"),
    
    
]

posts/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re

class TextEntry_a(models.Model):
    text_content = models.TextField("공지사항", blank=True)

    def __str__(self):
        return self.text_content
    
class TextEntry_b(models.Model):
    text_content = models.TextField("성경말씀", blank=True)

    def __str__(self):
        return self.text_content



class Post(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"
    





class Post2(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    content_a = models.TextField("호소한내용", blank=True)
    content_b = models.TextField("솔루션", blank=True)
    content_c = models.TextField("느낀점", blank=True)
    content_d = models.TextField("상담사례", blank=True)
    created2 = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)   
    
    tags_phone = models.CharField("전화번호",max_length=15, blank=True,help_text='숫자만 넣어주세요 : 0101231234')
    years_CHOICES = [ ('0', '모름'), ('1', '10대'),('2', '20대'),('3', '30대'),('4', '40대'),('5', '50대'),('6', '60대'),('7', '70대') ]
    tags_years = models.CharField("연령",max_length=1, choices=years_CHOICES,blank=True)
    GENDER_CHOICES = [        ('M', '남성'),        ('F', '여성'),  ]
    tags_gender = models.CharField("성별",max_length=1, choices=GENDER_CHOICES,blank=True)
    marriage = [('0', 'PASS'),('1', '기혼'),  ('2', '미혼'), ('3', '기타'),  ]
    tags_marriage = models.CharField("결혼여부",max_length=1, choices=marriage, blank=True)
    religion= [ ('0', 'PASS'),('1', '본교'),('2', '타교'),('3', '불신'),('4', '기타')]
    tags_religion = models.CharField("종교",max_length=1, choices=religion, blank=True,help_text='본교:1 타교:2 불신:3 기타:4')
 
    tags_position = models.CharField("직분",max_length=10, help_text='직분',blank=True)
    condition_A= [ ('0', 'PASS'),('1', '성숙'),('2', '미성숙'),('3', '양호'),('4', '기타')]
    tag_condition_A = models.CharField("신앙상태",max_length=1, choices=condition_A, blank=True,help_text='신앙상태 성숙:1 미성숙:2 양호:3 기타:4')
    condition_B= [ ('0', 'PASS'),('1', '안정'),('2', '불안정'),('3', '양호'),('4', '기타')]
    tag_condition_B = models.CharField("정서상태",max_length=1, choices=condition_B, blank=True,help_text='정서상태 안정:1 불안정:2 중간:3 기타:4')

    education = models.CharField("학력",max_length=10, blank=True,help_text='학력')
    job = models.CharField("직업",max_length=10, blank=True,help_text='직업')
    a_class_a = models.CharField("내용분류",max_length=10, blank=True,help_text='내용분류')
    consult_time = models.CharField("상담시간",max_length=3, blank=True,help_text='ex: 20분:20')
    

    def clean_phone_number(self):
        # 정규 표현식을 사용하여 숫자만 허용하는 유효성 검사        
        phone_number = self.phone_number
        if not re.match(r'^\+?\d+$', phone_number):
            raise ValidationError('Phone number can only contain digits.')

    def __str__(self):
        return f"{self.user.username}의 Post2(id: {self.id})"






class PostImage(models.Model):
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)



class Comment2(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post2, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

posts/views.py
from django.http import (
    HttpResponseBadRequest,
    HttpResponseRedirect,
    HttpResponseForbidden,
    HttpResponse,JsonResponse,
)
from django.shortcuts import render, redirect
from django.urls import reverse

from posts.forms import * 
from posts.models import *  
import os,random, csv
from django.utils import timezone
from datetime import timedelta,datetime



def to_admin(request):
    if request.user.is_staff:
        return redirect("posts:to_admin")
    else:
        return redirect("posts:feeds")



def index(req):
    post_latest = Post.objects.order_by("-createDate")[:6]
    
    context1 = {
        "post_latest": post_latest
    }
    return render(req, "index.html", context=context1)



def feeds(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("users:login")

    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, "posts/feeds.html", context)







def feeds2(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("users:login")#### 원래있던 자가 아니면 로그인페이지로
    

    if request.method == 'POST':
        form = DateRangeForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            print(end_date)
            now_date = timezone.now().date()
            print(now_date)

    else:             
        end_date = timezone.now().date() + timedelta(days=1)
        start_date = end_date - timedelta(days=30)   
        
    # posts = Post2.objects.all().order_by("-created2")[:100]
    # posts = Post2.objects.filter(created2__range=[start_date, end_date]).order_by("-created2")
    posts = Post2.objects.filter(
        created2__range=[
            timezone.make_aware(datetime.combine(start_date, datetime.min.time()), timezone.get_current_timezone()),
            timezone.make_aware(datetime.combine(end_date, datetime.max.time()), timezone.get_current_timezone())
        ]
    ).order_by("-created2")
    bible = TextEntry_b.objects.all().order_by('?')
    note1 = TextEntry_a.objects.all().order_by('?')

    bible1 = []    
    lll = bible.count()
    for i in range(posts.count()):
        k = i % lll
        bible1.append(bible[k])
    
    bbb = []  
    for a,b in zip(posts,bible1):
        c = {'posts':a,'bible':b}
        bbb.append(c)         

    comment_form = CommentForm()
    context = {
        "posts": bbb,
        "note": note1,
        "comment_form": comment_form,       
    }
   

    return render(request, "posts/feeds.html", context)


















# 댓글 작성을 처리할 View
def comment_add(request):
    if request.method == "GET":
        # 이 View에 GET요청이 전달되면, 잘못된 요청임을 브라우저에 알려준다.
        return HttpResponseBadRequest()
    # request.POST로 전달된 데이터를 사용해 CommentForm인스턴스를 생성
    form = CommentForm2(data=request.POST)
    if form.is_valid():
        # commit=False옵션으로 메모리상에 Comment객체 생성
        comment = form.save(commit=False)
        # Comment생성에 필요한 사용자정보를 request에서 가져와 할당
        comment.user = request.user
        # DB에 Comment객체 저장
        comment.save()
        # URL로 "next"값을 전달받았다면 댓글 작성 완료 후 전달받은 값으로 이동한다
        if request.GET.get("next"):
            url_next = request.GET.get("next")
        # "next"값을 전달받지 않았다면 피드페이지의 글 위치로 이동한다
        else:
            url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url_next)

# 댓글 작성을 처리할 View
def comment_addtag(request):
    print(1)
    if request.method == "GET":
        # 이 View에 GET요청이 전달되면, 잘못된 요청임을 브라우저에 알려준다.
        return HttpResponseBadRequest()
    # request.POST로 전달된 데이터를 사용해 CommentForm인스턴스를 생성
    form = CommentForm2(data=request.POST)
    if form.is_valid():
        # commit=False옵션으로 메모리상에 Comment객체 생성
        comment = form.save(commit=False)
        # Comment생성에 필요한 사용자정보를 request에서 가져와 할당
        comment.user = request.user
        # DB에 Comment객체 저장
        comment.save()
        # URL로 "next"값을 전달받았다면 댓글 작성 완료 후 전달받은 값으로 이동한다
        if request.GET.get("next"):
            url_next = request.GET.get("next")
            print(url_next)
        # "next"값을 전달받지 않았다면 피드페이지의 글 위치로 이동한다
        else:
            url_next = reverse("posts:tags")
        return HttpResponseRedirect(url_next)



def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment2.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    else:
        # 이 View에 오는 GET요청은 잘못되었다고 브라우저에 돌려준다
        return HttpResponseBadRequest()





def comment_delete2(request, comment_id):
    if request.method == "POST":
        comment = Comment2.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    else:
        # 이 View에 오는 GET요청은 잘못되었다고 브라우저에 돌려준다
        return HttpResponseBadRequest()





def post_delete(request, post_id):
    if request.method == "POST":
        post = Post2.objects.get(id=post_id) 
        # 여기에서 포스트 아이디를 받아온다. 
        ### post.id = 9 아이디 명을 보니 9번 포스트이다. 프린트 해보니
        # photo = PostImage.objects.get(pk = post.id)
        # 프라임키 id를 9번을 넣어주니 이 포스트의 url을 알 수 있다. 
        # print(photo.photo.url)
        if post.user == request.user: ### 내가 작성한 유저가 맞으면
            # 여기서 삭제해준다. 세팅에서 안되서 여기서는 그냥 때려 넣었다. 
            
            # os.remove("G:/python/20231201 django study first/bb_fgtv1"+photo.photo.url)
            post.delete()
            # 9번 포스트니 그냥 지워주면 그냥 지워진다. 
            url = reverse("posts:feeds") 
            return HttpResponseRedirect(url)
            # 여기서 리 다이렉트 url로 옮겨준다. 
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    else:
        # 이 View에 오는 GET요청은 잘못되었다고 브라우저에 돌려준다
        return HttpResponseBadRequest()








def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = PostForm(request.POST)

        if form.is_valid():
            # Post의 "user"값은 request에서 가져와 자동할당한다
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Post를 생성 한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage객체를 생성한다
            for image_file in request.FILES.getlist("images"):
                # request.FILES또는 request.FILES.getlist()로 가져온 파일은
                # Model의 ImageField부분에 곧바로 할당한다
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # "tags"에 전달 된 문자열을 분리해 HashTag생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_name_list = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_name_list:
                    tag, _ = HashTag.objects.get_or_create(
                        name=tag_name,
                    )
                    # get_or_create로 생성하거나 가져온 HashTag객체를 Post의 tags에 추가한다
                    post.tags.add(tag)

            # 모든 PostImage와 Post의 생성이 완료되면
            # 피드페이지로 이동하여 생성된 Post의 위치로 스크롤되도록 한다
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # GET요청일 때는 빈 form을 보여주도록한다
    else:        
        form = PostForm()

    context = {"form": form}
    return render(request, "posts/post_add.html", context)


#############################################
#############################################
#############################################
#############################################
#############################################
#############################################
#############################################
#############################################

def post_add2(request):
 
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리     
        form = PostForm2(request.POST) 

        if form.is_valid():
            # Post의 "user"값은 request에서 가져와 자동할당한다
            post = form.save(commit=False)
            post.user = request.user
            post.save() 

            # "tags"에 전달 된 문자열을 분리해 HashTag생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_name_list = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_name_list:
                    tag, _ = HashTag.objects.get_or_create(
                        name=tag_name,
                    )
                    # get_or_create로 생성하거나 가져온 HashTag객체를 Post의 tags에 추가한다
                    post.tags.add(tag)

            # 모든 PostImage와 Post의 생성이 완료되면
            # 피드페이지로 이동하여 생성된 Post의 위치로 스크롤되도록 한다
            url = reverse("posts:feeds") + f"#post-{post.id}"   
            return HttpResponseRedirect(url)

    # GET요청일 때는 빈 form을 보여주도록한다
    else:
        form = PostForm2()

    context = {"form": form}
    return render(request, "posts/post_add2.html", context)






def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우 빈 QuerySet을 돌려준다
        posts = Post2.objects.none()
    else:
        posts = Post2.objects.filter(tags=tag)

    # context로 Template에 필터링 된 Post QuerySet을 넘겨주며,
    # 어떤 tag_name으로 검색했는지도 넘겨준다
    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, "posts/tags.html", context)

templates/posts/admin1.html
<!doctype html>
{% load static %}
<html lang="ko">

<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Wonderful Counselor Jesus Christ</title>
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>

    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }


        function deleteRow(rowId) {
            // 선택한 행 삭제 로직
            const confirmDelete = confirm("정말로 삭제하시겠습니까?");
            if (confirmDelete) {
                // 서버에 삭제 요청을 보내는 부분
                fetch('delete_row/' + rowId, {
                    method: 'DELETE',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',  // CSRF 토큰 추가
                    },
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // 성공적으로 삭제되었을 때 화면에서 행 제거
                            const row = document.getElementById('row_' + rowId);
                            if (row) {
                                row.remove();
                            }
                        } else {
                            alert('삭제 실패');
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
            }
        }



        document.addEventListener("DOMContentLoaded", function () {
            // 오늘 날짜 가져오기
            var today = new Date();
            today.setDate(today.getDate() + 1);
            var todayFormatted = today.toISOString().split('T')[0];

            // 1달 전의 날짜 가져오기
            var oneMonthAgo = new Date();
            oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
            var oneMonthAgoFormatted = oneMonthAgo.toISOString().split('T')[0];

            // 폼 입력란에 초기 값 설정
            document.getElementById("id_start_date").value = oneMonthAgoFormatted;
            document.getElementById("id_end_date").value = todayFormatted;
        });

        function redirectToDownload() {
            var startDate = document.getElementById("id_start_date").value;
            var endDate = document.getElementById("id_end_date").value;
            var downloadUrl = "{% url 'posts:download_csv' %}?start_date=" + startDate + "&end_Date=" + endDate;
            window.location.href = downloadUrl;
        }
        function redirectToDownload2() {
            window.location.href = "{% url 'posts:admin2' %}";
        }
        function redirectToDownload3() {
            window.location.href = "{% url 'posts:admin3' %}";
        }





    </script>

    <style>
         body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            color: #007bff;
        }
        button.kmm {

            margin-left: 50px;
            margin-right: 30px;
        }

        table {
            width: 3000px;
            margin-top: 50px;
            margin-bottom: 50px;
            margin-right: 100px;
            border-collapse: collapse;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            overflow: hidden;
        }

        th,
        td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #315376;
            border: 1px solid #315376;
            padding: 8px;
        }

        th {
            background-color: #315376;
            color: white;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        .table-container {
            overflow-x: auto;
            margin-right: 50px;
            margin-left: 50px;
        }

        .kms {
            text-align: right;
            align-items: right;
            margin-left: 100px;
            margin-right: 100px;
        }

        .custom-button:hover {
        color: white;
        background-color: #0095f6;
        }



        
     


    </style>
</head>





<body>
    <nav>
        <h1>
            <a href="{% url 'posts:feeds' %}">Wonderful Counselor Jesus Christ</a>
        </h1>
        <a href="{% url 'posts:post_add2' %}">작성하기</a>
        <a href="#">{{user.first_name}}{{user.last_name}}</a>
        <a href="{% url 'users:logout' %}">Logout</a>

        {% if request.user.is_staff %}
        <a href="{% url 'posts:admin1' %}">관리자</a>
        {% else %}
        <a href="{% url 'posts:to_admin' %}">ㅇㅇㅇ</a>

        {% endif %}
    </nav>
    1<p>1
    <p>
    <p>
    <p></p>










    <form class="kms" method="post" action="{% url 'posts:date_range_view' %}?next={{ action_redirect_url }}">
        {% csrf_token %}
        <label for="startDate">검색 시작일:</label>
        <input type="date" id="id_start_date" name="start_date" required>


        <label for="endDate">검색 종료일:</label>
        <input type="date" id="id_end_date" name="end_date" required>

        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    
    
    
    <button class="kmm" onclick="redirectToDownload()">Download CSV</button>

    <button class="kmm" onclick="redirectToDownload2()">말씀추가</button>
    <button class="kmm" onclick="redirectToDownload3()">공지추가</button>

    
    






    <div class="table-container">

            <a class="kms" method="post" action="{% url 'posts:date_range_view' %}?next={{ action_redirect_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <a>
                    <table>
                        <thead>
                            <tr>
                                <th>글번호</th>
                                <th>아이디</th>
                                <th>작성일시</th>
                                <th>전화번호</th>
                                <th>연령</th>
                                <th>성별</th>
                                <th>결혼여부</th>
                                <th>종교</th>
                                <th>직분</th>
                                <th>신앙상태</th>
                                <th>정서상태</th>
                                <th>학력</th>
                                <th>직업</th>
                                <th>내용분류</th>
                                <th>상담시간</th>
                                <th>호소한내용</th>
                                <th>솔루션</th>
                                <th>느낀점</th>
                                <th>상담사례</th>
                                <th>tag</th>
                                <th>팀장확인</th>
                                <th>삭제</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for post in posts %}
                            <tr id="row_{{ post.id }}">
                                <td>{{ post.id }}</td>
                                <td>{{ post.user }}</td>
                                <td>{{ post.created2 }}</td>
                                <td>{{ post.tags_phone }}</td>
                                <td>{{ post.tags_years }}</td>
                                <td>{{ post.tags_gender }}</td>
                                <td>{{ post.tags_marriage }}</td>
                                <td>{{ post.tags_religion }}</td>
                                <td>{{ post.tags_position }}</td>
                                <td>{{ post.tag_condition_A }}</td>
                                <td>{{ post.tag_condition_B}}</td>                                
                                <td>{{ post.education }}</td>
                                <td>{{ post.job }}</td>
                                <td>{{ post.a_class_a }}</td>
                                <td>{{ post.consult_time }}</td>                                
                                <td>{{ post.content_a }}</td>
                                <td>{{ post.content_b }}</td>                                
                                <td>{{ post.content_c }}</td>
                                <td>{{ post.content_d }}</td>

                                <td>{% for tag in post.tags.all %}
                                    {{ tag.name }}
                                    {% endfor %}
                                </td>
                                <td>{{ post.like_users.count}}</td>
                                <td> {% if request.user.is_superuser %}
                                    <button onclick="deleteRow({{ post.id }})">삭제</button>
                                    {% else %}
                                    <button>권한없음</button>

                                    {% endif %}
                                </td>

                                <!-- 기타 필요한 데이터 추가 -->
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>


    </div>

    <p>1


</body>

</html>

templates/posts/feeds_삭제.html
{% load custom_tags %}


    
    {% block content %}


    <div id="feeds" class="post-container">
   
            {% for a in posts %}
                {{ a.posts}}<p>
                {{ a.bible}}<p>
                
              
                <!-- post = a.posts
                bible = a.bible -->
                       
               
            {% endfor %}
  
        </div>
    {% endblock %}

templates/posts/post1.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Random Text Entry Feed</title>
</head>
<body>

<div class="post-comment-create">
    {% if random_entry %}
        <h1>Random Text Entry</h1>
        <p>{{ random_entry }}</p>
        <p>123</p>
        <!-- 기타 필요한 정보들을 표시하거나 스타일링을 추가할 수 있습니다. -->
    {% else %}
        <p>없슈</p>
    {% endif %}
</div>

</body>
</html>

templates/posts/post_add.html
{% extends 'base_nav.html' %}

{% block content %}
    <div id="post-add">
        <h1>Post 작성</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <!-- label의 for속성에는 가리키는 input의 id값을 입력 -->
                <label for="id_images">이미지</label>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <div>
                <label for="id_tags">해시태그</label>
                <input id="id_tags" name="tags" type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
            </div>
            <button type="submit">게시</button>
        </form>
    </div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}
    <div id="feeds" class="post-container">
        {% url 'posts:post_detail2' post.id as action_redirect_to %}
        {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
    </div>
{% endblock %}