config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
    
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

posts/urls.py
from django.urls import path

from posts.views import *
# (*
#     feeds,
#     comment_add,
#     comment_delete,
#     post_add,
#     tags,
#     post_detail,
#     post_like,
#     post_delete,
# )

app_name = "posts"
urlpatterns = [

    # path("comments/<int:comment_id>/delete/", comment_delete, name="comment_delete"),
    # path("post_add/", post_add, name="post_add"),
    # path("<int:post_id>/", post_detail, name="post_detail"),
    # path("post/<int:post_id>/delete/", post_delete, name="post_delete"),    
    # path("comment_add/", comment_add2, name="comment_add2"),


    path("feeds/", feeds2, name="feeds"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("tags/<str:tag_name>/", tags2, name="tags2"),
    path("<int:post2_id>/", post_detail2, name="post_detail2"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_addtag/", comment_addtag, name="comment_addtag"),

    path("<int:post2_id>/like/", post_like2, name="post_like2"),
    path("post_add/", post_add, name="post_add"),
    
    path("post_add2/", post_add2, name="post_add2"),
    path("comments/<int:comment_id>/delete/", comment_delete2, name="comment_delete2"),

    path('text_entry_list/', text_entry_list, name='text_entry_list'),
    path("admin1/aa/", admin1, name="admin1"),
    path("date_range_view/delete_row/<int:row_id>", delete_row, name="delete_row"),
    path("admin1/aa/delete_row/<int:row_id>", delete_row, name="delete_row"),

    path("admin2/delete_row2/<int:row_id>", delete_row2, name="delete_row2"),
    path("admin2/", admin2, name="admin2"),
    path('create/', create_text_entry, name='create_text_entry'),
    
    path('admin1/aa/', date_range_view, name='date_range_view'),
    path('download_csv/', download_csv, name='download_csv'), #### 추가한다. 

    path('../../admin/', to_admin, name='to_admin'), #### 추가한다. 
    path("admin3/", admin3, name="admin3"),
    path('create_note/', create_text_entry_note, name='create_text_entry_note'),#### 여기는 공지사항
    path("admin3/delete_row3/<int:row_id>", delete_row3, name="delete_row3"),
]

users/urls.py
from django.urls import path

from users.views import *
# (
#     login_view,
#     logout_view,
#     signup,
#     profile,
#     followers,
#     following,
#     follow,
# )

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
 
 
    path("<int:user_id>/profile/", profile2, name="profile2"),
    path("my_update/", my_update, name="my_update"),
    
    
]

posts/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re

class TextEntry_a(models.Model):
    text_content = models.TextField("공지사항", blank=True)

    def __str__(self):
        return self.text_content
    
class TextEntry_b(models.Model):
    text_content = models.TextField("성경말씀", blank=True)

    def __str__(self):
        return self.text_content



class Post(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"
    





class Post2(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    content_a = models.TextField("호소한내용", blank=True)
    content_b = models.TextField("솔루션", blank=True)
    content_c = models.TextField("느낀점", blank=True)
    content_d = models.TextField("상담사례", blank=True)
    created2 = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)   
    
    tags_phone = models.CharField("전화번호",max_length=15, blank=True,help_text='숫자만 넣어주세요 : 0101231234')
    years_CHOICES = [ ('0', '모름'), ('1', '10대'),('2', '20대'),('3', '30대'),('4', '40대'),('5', '50대'),('6', '60대'),('7', '70대') ]
    tags_years = models.CharField("연령",max_length=1, choices=years_CHOICES,blank=True)
    GENDER_CHOICES = [        ('M', '남성'),        ('F', '여성'),  ]
    tags_gender = models.CharField("성별",max_length=1, choices=GENDER_CHOICES,blank=True)
    marriage = [('0', 'PASS'),('1', '기혼'),  ('2', '미혼'), ('3', '기타'),  ]
    tags_marriage = models.CharField("결혼여부",max_length=1, choices=marriage, blank=True)
    religion= [ ('0', 'PASS'),('1', '본교'),('2', '타교'),('3', '불신'),('4', '기타')]
    tags_religion = models.CharField("종교",max_length=1, choices=religion, blank=True,help_text='본교:1 타교:2 불신:3 기타:4')
 
    tags_position = models.CharField("직분",max_length=10, help_text='직분',blank=True)
    condition_A= [ ('0', 'PASS'),('1', '성숙'),('2', '미성숙'),('3', '양호'),('4', '기타')]
    tag_condition_A = models.CharField("신앙상태",max_length=1, choices=condition_A, blank=True,help_text='신앙상태 성숙:1 미성숙:2 양호:3 기타:4')
    condition_B= [ ('0', 'PASS'),('1', '안정'),('2', '불안정'),('3', '양호'),('4', '기타')]
    tag_condition_B = models.CharField("정서상태",max_length=1, choices=condition_B, blank=True,help_text='정서상태 안정:1 불안정:2 중간:3 기타:4')

    education = models.CharField("학력",max_length=10, blank=True,help_text='학력')
    job = models.CharField("직업",max_length=10, blank=True,help_text='직업')
    a_class_a = models.CharField("내용분류",max_length=10, blank=True,help_text='내용분류')
    consult_time = models.CharField("상담시간",max_length=3, blank=True,help_text='ex: 20분:20')
    

    def clean_phone_number(self):
        # 정규 표현식을 사용하여 숫자만 허용하는 유효성 검사        
        phone_number = self.phone_number
        if not re.match(r'^\+?\d+$', phone_number):
            raise ValidationError('Phone number can only contain digits.')

    def __str__(self):
        return f"{self.user.username}의 Post2(id: {self.id})"






class PostImage(models.Model):
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)



class Comment2(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post2, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

templates/_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Wonderful Counselor Jesus Christ</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}
</body>
</html>

templates/base.html
{% extends '_base.html' %}

{% block base_content %}
    {% block content %}{% endblock %}
{% endblock %}

templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        <!-- 프로필 이미지 영역 -->
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <!-- 사용자 정보 영역 -->
        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts게시물 {{ posts.count }}</dt>
                    <dd>
                        <a href="{% url 'users:profile2' user_id=user.id %}">{{ user.post_set.count }}</a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'users:followers' user_id=user.id %}">{{ user.followers.count }}</a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'users:following' user_id=user.id %}">{{ user.following.count }}</a>
                    </dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
        </div>
    </div>
    {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
  
    {% block content %}
    {% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }


        document.addEventListener("DOMContentLoaded", function () {
        // 오늘 날짜 가져오기
        var today = new Date();
        today.setDate(today.getDate() + 1);
        var todayFormatted = today.toISOString().split('T')[0];

        // 1달 전의 날짜 가져오기
        var oneMonthAgo = new Date();
        oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
        var oneMonthAgoFormatted = oneMonthAgo.toISOString().split('T')[0];

        // 폼 입력란에 초기 값 설정
        document.getElementById("id_start_date").value = oneMonthAgoFormatted;
        document.getElementById("id_end_date").value = todayFormatted;
         });


        
      

    </script>
    <style>
        
        .postkmmm {        
            padding: 10px;
            box-sizing: border-box;
            border-left: 100px solid #ffffff;
            border-right: 1px solid #ddd;
            border-bottom: 1px solid #eee;
           
        }
    </style>
{% endblock %}

templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Wonderful Counselor Jesus Christ</a>
    </h1>
    
    <a href="{% url 'posts:post_add2' %}">작성하기</a>
    <a href="#">{{user.first_name}}{{user.last_name}}</a>
    <a href="{% url 'users:logout' %}">Logout</a>

    {% if request.user.is_staff %}
        <a href="{% url 'posts:admin1' %}">관리자</a>        
    {% endif %}
</nav>